### PR TITLE
Add `onNote` for triggering events when a note is pressed

### PR DESCRIPTION
**Pull request by geikha**
This would be useful for multiple reasons. But the most hydra-related one would be being able to change the sketch on the press of a note. On a live setting, this makes it possible for a VJ to set different "scenes" and change between them. On a production setting, this would make it super easy to sequence sketches from a DAW in order to, for example, code a music video for a song.

This PR hasn't been tested! Will test tomorrow.

---

### Syntax

I've coded it so that `.onNote(noteName, event)` can be accessed via a `input` or `channel`. When used from `input`, the channel is simply `'*'`

Example
```js
device = midi.input(0)

device.onNote('c1', () => {
    osc().out()
})
```

Edit: renamed to onNote

### CODE REVIEW

**Comment by arnoson** [comment]
This looks great, thanks for the PR! Will also test it on monday. If have only one question: would you mind renaming `onnote` to `onNote`? This is just a personal preference.

**Comment by geikha** [comment]
of course ! that was actually my first idea too but idk why I just had the feeling you might prefer it all lowercase lol

**Comment by geikha** [comment]
all done! tested on windows using FL Studio and loopMidi and fixed some stuff. should be ready to go

**Comment by arnoson** [comment]
awesome, thanks! I'll have a look at it tomorrow or on monday and merge it

**Comment by arnoson** [comment]
Found some time this evening to merge :) New version can be loaded with `@latest` or `@0.1.0` https://cdn.jsdelivr.net/gh/arnoson/hydra-midi@latest/dist/index.js

**Comment by geikha** [comment]
would you like me to share this on the discord server? i feel many people haven't realized this is already a regular script extension instead of the old chrome extension. (i realized just a couple days ago personally)

**Comment by arnoson** [comment]
ah yes please share it!

**Pull request merged**
